services:
  db:
    container_name: postgresql
    image: postgres:15
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
      POSTGRES_DB: website
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - srvnet
    restart: unless-stopped

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php83
    volumes:
      - ./src/www:/var/www/public
    networks:
      - srvnet
    restart: unless-stopped
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/www:/var/www/public
      - ./docker/nginx:/etc/nginx/conf.d
      - /srv/http/ssl:/ssl
    depends_on:
      - php
    networks:
      - srvnet
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  srvnet:
    name: srvnet
    driver: bridge
